#############################
# SSH Pipeline Script
#   Bitbucket to AWS
#
#  Creator: Mindit
#  Version: 1.0
#  
#  Version History:
#  1.0 Initial version
#
#############################
image: python:3.5.1

pipelines:
  default:
    - step:
        script:
          - echo "Host git-codecommit.*.amazonaws.com" > /root/.ssh/config
          - echo "  User ${AWS_SSH_ID}" >> /root/.ssh/config
          - echo "  IdentityFile /opt/atlassian/pipelines/agent/data/id_rsa" >> /root/.ssh/config
          - git push --mirror ${AWS_SSH_URL}